# Use a imagem oficial do MariaDB como base
FROM mariadb:latest

# Defina a variável de ambiente MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD='123456'

# Defina a variável de ambiente MYSQL_DATABASE se desejar criar um banco de dados padrão
# ENV MYSQL_DATABASE=nome_do_banco

# Expor a porta 3306 (a porta padrão do MariaDB)
EXPOSE 3306
